// <auto-generated />
namespace Reports_Manager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_articles_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_articles_database));
        
        string IMigrationMetadata.Id
        {
            get { return "201604060920451_add_articles_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
